"""
Django settings for wrsms_project project.

Generated by 'django-admin startproject' using Django 5.2.1.
"""

import os
from pathlib import Path
import environ

# Initialize environment variables
env = environ.Env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file from the project root
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])

# Application definition
INSTALLED_APPS = [
    'account.apps.AccountConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'wrsm_app',
    'crispy_forms',
    'crispy_tailwind',
    'widget_tweaks',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'corsheaders',
    'pwa',
]

CLOUDINARY_URL = (env('CLOUDINARY_URL', default='') or '').strip().strip('"').strip("'")
# Only enable when URL looks valid (whitespace alone must not turn Cloudinary on).
USE_CLOUDINARY = CLOUDINARY_URL.startswith('cloudinary://')

if USE_CLOUDINARY:
    INSTALLED_APPS += [
        'cloudinary_storage',
        'cloudinary',
    ]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'wrsm_app.middleware.SubscriptionMiddleware',
]

ROOT_URLCONF = 'wrsms_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wrsm_app.context_processors.global_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'wrsms_project.wsgi.application'

# Database - PostgreSQL only
# Set DATABASE_URL in .env (e.g. postgres://user:password@localhost:5432/dbname)
DATABASES = {
    'default': env.db('DATABASE_URL'),
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Manila'
USE_THOUSAND_SEPARATOR = True
USE_L10N = True
USE_I18N = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = env('STATIC_ROOT', default=os.path.join(BASE_DIR, 'staticfiles'))

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = env('MEDIA_ROOT', default=os.path.join(BASE_DIR, 'media'))

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    # Avoid Manifest storage on PaaS: missing/wrong manifest entries cause 500 on every page.
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

if USE_CLOUDINARY:
    STORAGES['default'] = {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    }

# Auth Redirects
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/account/login/'
LOGIN_URL = '/account/login/'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACK = 'tailwind'
CRISPY_TEMPLATE_PACK = 'tailwind'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=["http://localhost:3000"])

# PWA Settings

PWA_APP_NAME = 'SmartDynamic Refilling'

PWA_APP_DESCRIPTION = "Smart Dynamic Refilling System"

PWA_APP_THEME_COLOR = '#0ea5e9'

PWA_APP_BACKGROUND_COLOR = '#e2e8f0'

PWA_APP_DISPLAY = 'standalone'

PWA_APP_SCOPE = '/'

PWA_APP_ORIENTATION = 'any'

PWA_APP_START_URL = '/'

PWA_APP_STATUS_BAR_COLOR = 'default'

PWA_APP_ICONS = [
    {
        'src': '/static/img/SDR_thumbnail.png',
        'sizes': '192x192',
        'type': 'image/png'
    },
    {
        'src': '/static/img/SDR_thumbnail.png',
        'sizes': '512x512',
        'type': 'image/png'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/img/SDR_thumbnail.png',
        'sizes': '192x192 512x512',
        'type': 'image/png'
    }
]


PWA_APP_SPLASH_SCREEN = [{'src': '/static/img/SDR_thumbnail.png', 'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'}]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-us'
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static', 'serviceworker.js')


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtpout.secureserver.net')
EMAIL_PORT = env.int('EMAIL_PORT', default=465)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=False)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='WRSMS Support <rvloquillano07@gmail.com>')
GCASH_ACCOUNT_NAME = env('GCASH_ACCOUNT_NAME', default='RONEL VINCENT CASEÑAS LOQUILLANO')
GCASH_ACCOUNT_NUMBER = env('GCASH_ACCOUNT_NUMBER', default='09669733621')


# Render sets RENDER=true; local disk for logs can be read-only or fail on startup.
_IS_RENDER = os.environ.get('RENDER', '').lower() in ('1', 'true', 'yes')

# --- PRODUCTION SECURITY SETTINGS ---
if not DEBUG:
    # Proxy Security (Crucial for Nginx/Gunicorn)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # SSL/HTTPS Redirects
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)

    # Session & CSRF Security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Logging: avoid FileHandler on Render (startup can fail if path is not writable).
    _django_handlers = ['console'] if _IS_RENDER else ['file', 'console']
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
            **({} if _IS_RENDER else {
                'file': {
                    'level': 'ERROR',
                    'class': 'logging.FileHandler',
                    'filename': os.path.join(BASE_DIR, 'django_error.log'),
                },
            }),
        },
        'loggers': {
            'django': {
                'handlers': _django_handlers,
                'level': 'ERROR',
                'propagate': True,
            },
        },
    }