from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from . import views_offline

app_name = 'wrsm_app'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('switch-station/<int:station_id>/', views.switch_station, name='switch-station'),
    path('home/', views.home, name='home'),
    path('setup-wizard/', views.setup_wizard, name='setup-wizard'),
    path('api/offline-master-data/', views_offline.get_offline_master_data, name='offline_master_data'),
    path('add-station-settings/', views.add_station_settings, name='add-station-settings'),
    path('station-setting-detail/', views.StationSettingDetail.as_view(), 
         name='station-setting-detail'),
    path('station-setting-update/', views.StationSettingUpdateView.as_view(), 
         name='station-setting-update'),
    path('add-net-terms/', views.add_net_terms, name='add-net-terms'),
    path('net-terms/', views.NetTermsListView.as_view(), name='net-terms'),
    path('add-customer/', views.add_customer, name='add-customer'),
    path('customers/', views.CustomersListView.as_view(), name='customers'),
    path('customer-map/', views.customer_map, name='customer-map'),
    path('delivery-map/', views.delivery_map, name='delivery-map'),
    path('customer-detail/<int:pk>/', views.CustomerDetail.as_view(), name='customer-detail'),
    path('update-customer/<int:pk>/', views.CustomerUpdateView.as_view(), name='update-customer'),
    path('add-size/', views.add_size, name='add-size'),
    path('sizes/', views.SizesListView.as_view(), name='sizes'),
    path('add-shortcut/', views.add_shortcut, name='add-shortcut'),
    path('shortcuts/', views.ShortcutsListView.as_view(), name='shortcuts'),
    path('update-shortcuts/<int:pk>/', views.ShortcutUpdateView.as_view(), name='update-shortcut'),
    path('process-shortcut/<int:pk>/', views.process_shortcut, name='process-shortcut'),
    path('add-order-type/<int:pk>/', views.add_order_type, name='add-order-type'),
    path('order-types/<int:pk>/', views.OrderTypesListView.as_view(), name='order-types'),
    path('sales/', views.SalesListView.as_view(), name='sales'),
    path('add-sales/', views.add_sales, name='add-sales'),
    path('add-sales-from-order/<int:order_id>/', views.add_sales_from_order, name='add-sales-from-order'),
    path('promos/', views.PromosListView.as_view(), name='promos'),
    path('add-promo/', views.add_promo, name='add-promo'),
    path('products/', views.ProductListView.as_view(), name='products'),
    path('add-jug-type/', views.add_jug_type, name='add-jug-type'),
    path('jug-types/', views.JugTypeListView.as_view(), name='jug-types'),
    path('add-product/', views.add_product, name='add-product'),
    path('update-product/<int:pk>/', views.ProductUpdateView.as_view(), name='update-product'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('add-order/', views.add_order, name='add-order'),
    path('update-order/<int:pk>/<int:order_id>/', views.OrderUpdateView.as_view(), name='update-order'),
    path('delete-promo/<int:pk>/', views.delete_promo, name='delete-promo'),
    path('delete-size/<int:pk>/', views.delete_size, name='delete-size'),
    path('add-order-type/', views.add_order_type, name='add-order-type'),
    path('order-types/', views.OrderTypesListView.as_view(), name='order-types'),
    path('add-payment-type/', views.add_payment_type, name='add-payment-type'),
    path('payment-types/', views.PaymentTypesListView.as_view(), name='payment-types'),
    path('add-discount/', views.add_discount, name='add-discount'),
    path('discounts/', views.DiscountsListView.as_view(), name='discounts'),
    path('backwash-monitor/', views.backwash_monitor, name='backwash-monitor'),
    path('maintenance/', views.MaintenanceListView.as_view(), name='maintenance'),
    path('add-maintenance/', views.add_maintenance, name='add-maintenance'),
    path('expenses/', views.ExpensesListView.as_view(), name='expenses'),
    path('add-container-inventory/', views.add_container_inventory, name='add-container-inventory'),
    path('container-inventory-list/', views.ContainerInventoryListView.as_view(), 
         name='container-inventory-list'),
    path('add-expense/', views.add_expense, name='add-expense'),
    path('cancel-order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('process-order/<int:order_id>/', views.process_order, name='process_order'),
    path('order-forecast/', views.ForecastListView.as_view(), name='order-forecast'),
    path('add-forecast/<int:pk>/', views.add_forecast, name='add-forecast'),
    path('forecast-update/', views.update_forecast, name='update_forecast'),
    path('forecast-customer-update/<int:pk>/', views.ForecastCustomerUpdateView.as_view(), 
         name='forecast-customer-update'),
 
    path('financial-report/', views.monthly_financial_report, name='monthly-financial-report'),
    path('add-payment/<int:customer_id>/', views.add_payment, name='add-payment'),
    path('add-payment-generic/<int:pk>/<int:sales_id>/', views.add_payment_generic, name='add-payment-generic'),
    path('ar-list/', views.ARListView.as_view(), name='ar-list'),
 
    # path('update-payment/<int:pk>/', views.update_payment, name='update-payment'),
    path('ajax/get-customer-data/', views.get_customer_data, name='get_customer_data'),
    path('ajax/get-payment-item-data/', views.get_payment_item_data, name='get_payment_item_data'),
    path('ajax/get-product-data/', views.get_product_data, name='get_product_data'),
    path('ajax/get-container-balance/', views.get_container_balance, name='get_container_balance'),
    path('ajax/get-ordertype-data/', views.get_ordertype_data, name='get_ordertype_data'),
    path('ajax/get-jugsize-data/', views.get_jugsize_data, name='get_jugsize_data'),
    path('ajax/get-finance-data/', views.get_finance_data, name='get_finance_data'),
    path('ajax/get-forecast-data/', views.get_forecast_data, name='get_forecast_data'),
] + static(settings.STATIC_URL, document_root=settings.BASE_DIR / "static")
