# Generated by Django 5.2.1 on 2025-09-13 10:17

import django.db.models.deletion
import wrsm_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purok', models.CharField(blank=True, max_length=100, null=True)),
                ('brgy', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('location_image', models.ImageField(blank=True, null=True, upload_to=wrsm_app.models.customer_image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(blank=True, max_length=20, null=True)),
                ('discount_rate', models.FloatField()),
                ('discount_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JugSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(max_length=10)),
                ('size_in_liters', models.FloatField(blank=True, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jug Size',
            },
        ),
        migrations.CreateModel(
            name='NetTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_label', models.CharField(max_length=50)),
                ('terms_in_days', models.PositiveIntegerField(default=0)),
                ('terms_description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'net terms',
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('unit_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'order type',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sort_number', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'payment type',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=20)),
                ('promo_description', models.CharField(max_length=100)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('station_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.customer')),
            ],
            options={
                'verbose_name_plural': 'accounts receivable',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.discount'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('utilities', 'Utilities'), ('salaries', 'Salaries & Wages'), ('rent', 'Rent'), ('transportation', 'Transportation'), ('supplies', 'Supplies'), ('repairs', 'Repairs & Maintenance'), ('marketing', 'Marketing'), ('licenses', 'Licensing & Permits'), ('software', 'Software & Tools'), ('professional', 'Professional Services'), ('bank_fees', 'Bank Fees'), ('insurance', 'Insurance'), ('misc', 'Miscellaneous')], max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='wrsm_app.expense')),
            ],
            options={
                'verbose_name_plural': 'expense item',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='net_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.netterms'),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.ordertype'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='wrsm_app.customer')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.paymenttype')),
            ],
            options={
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('accounts_receivable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_payment_items', to='wrsm_app.accountsreceivable')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='wrsm_app.payment')),
            ],
            options={
                'verbose_name_plural': 'payment items',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, choices=[('REFILL', 'REFILL'), ('JUG', 'JUG'), ('SPARE PART', 'SPARE PART'), ('DELIVERY CHARGE', 'DELIVERY CHARGE'), ('OTHER', 'OTHER')], max_length=50, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('jug_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.jugsize')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.station')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGeneric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_id', models.CharField(max_length=10, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.paymenttype')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.profile'),
        ),
        migrations.AddField(
            model_name='netterms',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.profile'),
        ),
        migrations.CreateModel(
            name='CustomerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='wrsm_app.customer')),
                ('source_of_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.payment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.profile')),
            ],
            options={
                'verbose_name_plural': 'customer credits',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.promo'),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.profile')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.customer')),
                ('order_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.ordertype')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station')),
            ],
            options={
                'verbose_name_plural': 'sales',
            },
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_records', to='wrsm_app.sales'),
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_liters', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_products', to='wrsm_app.product')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='wrsm_app.sales')),
            ],
        ),
        migrations.CreateModel(
            name='ShortCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_note', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('prompt_quantity', models.BooleanField(default=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.profile')),
                ('order_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.ordertype')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.product')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station')),
            ],
            options={
                'verbose_name_plural': 'shortcuts',
            },
        ),
        migrations.AddField(
            model_name='promo',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station'),
        ),
        migrations.AddField(
            model_name='ordertype',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_note', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.customer')),
                ('order_type', models.ForeignKey(default='Delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.ordertype')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.paymenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='wrsm_app.profile')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station')),
            ],
        ),
        migrations.AddField(
            model_name='netterms',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('backwash', 'backwash'), ('cleaning', 'cleaning'), ('filter change', 'filter change'), ('repair', 'repair'), ('other', 'other')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station')),
            ],
        ),
        migrations.AddField(
            model_name='jugsize',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station'),
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_frequency', models.PositiveIntegerField(blank=True, help_text='Number of days between orders', null=True)),
                ('last_order_date', models.DateField(blank=True, null=True)),
                ('next_order_date', models.DateField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.customer')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station')),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station'),
        ),
        migrations.CreateModel(
            name='CustomerGeneric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.sales')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station'),
        ),
        migrations.CreateModel(
            name='ContainerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('balance_from_last_visit', models.IntegerField(default=0)),
                ('delivered_container', models.IntegerField(default=0)),
                ('returned_empty_container', models.IntegerField(default=0)),
                ('new_balance', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.customer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.profile')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station')),
            ],
            options={
                'verbose_name_plural': 'container inventory',
            },
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station'),
        ),
        migrations.CreateModel(
            name='StationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_delivery_rate', models.FloatField()),
                ('default_unit_price', models.FloatField()),
                ('default_minimum_delivery_qty', models.IntegerField()),
                ('days_to_filter_saleslist', models.IntegerField(blank=True, default=1, help_text='Number of days to filter sales list', null=True)),
                ('num_of_liters_to_backwash', models.IntegerField(blank=True, null=True)),
                ('num_of_liters_to_change_filter', models.IntegerField(blank=True, null=True)),
                ('default_jug_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.jugsize')),
                ('default_order_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.ordertype')),
                ('default_payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.paymenttype')),
                ('station', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station')),
            ],
            options={
                'verbose_name_plural': 'station setting',
            },
        ),
    ]
