# Generated by Django 5.2.1 on 2025-09-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationsetting',
            name='auto_deduct_supplies',
            field=models.BooleanField(default=False, help_text='Auto deduct supplies when sales is made'),
        ),
    ]
