# Generated by Django 5.2.1 on 2025-09-25 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0002_stationsetting_auto_deduct_supplies'),
    ]

    operations = [
        migrations.CreateModel(
            name='JugType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jug_type', models.CharField(blank=True, max_length=20, null=True)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station')),
            ],
            options={
                'verbose_name_plural': 'Jug Size',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='jug_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.jugtype'),
        ),
    ]
