# Generated by Django 5.2.1 on 2025-09-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0003_jugtype_product_jug_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugtype',
            options={'verbose_name_plural': 'Jug Type'},
        ),
    ]
