# Generated by Django 5.2.1 on 2025-09-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0004_alter_jugtype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('REFILL', 'REFILL'), ('JUG', 'JUG'), ('SEAL', 'SEAL'), ('SPARE PART', 'SPARE PART'), ('DELIVERY CHARGE', 'DELIVERY CHARGE'), ('OTHER', 'OTHER')], max_length=50, null=True),
        ),
    ]
