# Generated by Django 5.2.1 on 2025-10-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0005_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationsetting',
            name='initial_jug_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
