# Generated by Django 5.2.1 on 2025-10-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0006_stationsetting_initial_jug_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugtype',
            name='jug_type',
            field=models.CharField(blank=True, choices=[('round', 'round'), ('slim', 'slim'), ('slim with faucet', 'slim with faucet'), ('square', 'square'), ('other', 'other')], default='round', max_length=20, null=True),
        ),
    ]
