# Generated by Django 5.2.1 on 2025-12-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0007_alter_jugtype_jug_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='netterms',
            constraint=models.UniqueConstraint(fields=('station', 'terms_label'), name='unique_terms_label_per_station'),
        ),
    ]
