# Generated by Django 5.2.1 on 2025-12-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0008_netterms_unique_terms_label_per_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='client_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
