# Generated by Django 5.2.1 on 2025-12-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0009_sales_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='client_id',
        ),
    ]
