# Generated by Django 5.2.1 on 2025-12-19 06:27
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0012_auto_20251219_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='client_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
