# Generated by Django 5.2.1 on 2025-12-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0013_auto_20251219_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='client_uuid',
        ),
    ]
