# Generated by Django 5.2.1 on 2025-12-19 15:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0014_remove_sales_client_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='client_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
