# Generated by Django 5.2.1 on 2025-12-19 15:05

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("wrsm_app", "Sales")
    for row in MyModel.objects.all():
        row.client_uuid = uuid.uuid4()
        row.save(update_fields=["client_uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0015_sales_client_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
