# Generated by Django 5.2.1 on 2025-12-19 19:33

from django.db import migrations
import uuid


def gen_uuid_order(apps, schema_editor):
    MyModel = apps.get_model("wrsm_app", "Order")
    for row in MyModel.objects.all():
        row.client_uuid = uuid.uuid4()
        row.save(update_fields=["client_uuid"])

def gen_uuid_customer(apps, schema_editor):
    MyModel = apps.get_model("wrsm_app", "Customer")
    for row in MyModel.objects.all():
        row.client_uuid = uuid.uuid4()
        row.save(update_fields=["client_uuid"])

def gen_uuid_containerinventory(apps, schema_editor):
    MyModel = apps.get_model("wrsm_app", "ContainerInventory")
    for row in MyModel.objects.all():
        row.client_uuid = uuid.uuid4()
        row.save(update_fields=["client_uuid"])

def gen_uuid_payment(apps, schema_editor):
    MyModel = apps.get_model("wrsm_app", "Payment")
    for row in MyModel.objects.all():
        row.client_uuid = uuid.uuid4()
        row.save(update_fields=["client_uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0018_containerinventory_client_uuid_customer_client_uuid_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid_order, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_uuid_customer, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_uuid_containerinventory, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_uuid_payment, reverse_code=migrations.RunPython.noop),
    ]
