# Generated by Django 5.2.1 on 2025-12-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0020_auto_20251219_1933'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='netterms',
            name='unique_terms_label_per_station',
        ),
        migrations.RemoveField(
            model_name='containerinventory',
            name='client_uuid',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='client_uuid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_uuid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client_uuid',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='client_uuid',
        ),
    ]
