# Generated by Django 5.2.1 on 2025-12-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0021_remove_netterms_unique_terms_label_per_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
