# Generated by Django 5.2.1 on 2025-12-23 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0023_remove_sales_client_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsreceivable',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AddField(
            model_name='containerinventory',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containerinventory_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AddField(
            model_name='customercredit',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customercredit_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AddField(
            model_name='customergeneric',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customergeneric_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AddField(
            model_name='expense',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AddField(
            model_name='paymentgeneric',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentgeneric_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AddField(
            model_name='sales',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AddField(
            model_name='shortcut',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortcut_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AddField(
            model_name='stationsetting',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stationsetting_modified_by', to='wrsm_app.profile'),
        ),
    ]
