# Generated by Django 5.2.1 on 2025-12-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0024_accountsreceivable_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationsetting',
            name='gcash_account',
            field=models.CharField(blank=True, help_text='Gcash account number for payments', max_length=50, null=True),
        ),
    ]
