# Generated by Django 5.2.1 on 2025-12-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0025_stationsetting_gcash_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationsetting',
            name='gcash_account_name',
            field=models.CharField(blank=True, help_text='Gcash account name for payments', max_length=100, null=True),
        ),
    ]
