# Generated by Django 5.2.1 on 2025-12-24 08:13

import wrsm_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0026_stationsetting_gcash_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationsetting',
            name='gcash_account_name',
        ),
        migrations.AddField(
            model_name='stationsetting',
            name='gcash_qr_image',
            field=models.ImageField(blank=True, help_text='Upload your personal GCash QR code image', null=True, upload_to=wrsm_app.models.station_image_upload_path),
        ),
    ]
