# Generated by Django 5.2.1 on 2025-12-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0027_remove_stationsetting_gcash_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_stations',
            field=models.ManyToManyField(blank=True, related_name='allowed_profiles', to='wrsm_app.station'),
        ),
    ]
