# Generated by Django 5.2.1 on 2025-12-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0028_profile_allowed_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
