# Generated by Django 5.2 on 2025-12-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0029_customer_latitude_customer_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugtype',
            name='jug_type',
            field=models.CharField(blank=True, default='round', max_length=50, null=True),
        ),
    ]
