# Generated by Django 5.2.1 on 2025-12-28 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0031_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'Add'), ('EDIT', 'Edit'), ('DELETE', 'Delete')], max_length=10)),
                ('target_model', models.CharField(max_length=50)),
                ('target_object_id', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.profile')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrsm_app.station')),
            ],
        ),
    ]
