# Generated by Django 5.2.1 on 2025-12-28 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0032_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsreceivable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_created', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='accountsreceivable',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='containerinventory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_inventory_created', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='containerinventory',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containerinventory_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='customercredit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_created', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='customercredit',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customercredit_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='customergeneric',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_generic_created', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='customergeneric',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customergeneric_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_created', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='netterms',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='netterms_created', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='paymentgeneric',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentgeneric_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='paymentgeneric',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_payments_received', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_created', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortcuts_created', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortcut_modified_by', to='wrsm_app.profile'),
        ),
        migrations.AlterField(
            model_name='stationsetting',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stationsetting_modified_by', to='wrsm_app.profile'),
        ),
    ]
