# Generated by Django 5.2 on 2025-12-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0033_alter_accountsreceivable_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
