# Generated by Django 5.2.1 on 2025-12-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0034_station_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='branch',
            field=models.CharField(blank=True, help_text='Location of this branch', max_length=100, null=True),
        ),
    ]
