# Generated by Django 5.2 on 2026-01-02 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0037_remove_order_order_date_alter_order_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_offline',
            field=models.BooleanField(default=False, help_text='Indicates if this order was created while offline'),
        ),
        migrations.AddField(
            model_name='order',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when offline order was synced to server', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrsm_app.ordertype'),
        ),
    ]
