# Generated by Django 5.2 on 2026-01-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0038_add_offline_fields_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_offline',
            field=models.BooleanField(default=False, help_text='Indicates if this customer was created while offline'),
        ),
        migrations.AddField(
            model_name='customer',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when offline customer was synced to server', null=True),
        ),
    ]
