# Generated by Django 5.2 on 2026-01-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0039_rename_container_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugsize',
            name='unit_price',
        ),
    ]
