# Generated by Django 5.2 on 2026-01-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0040_remove_jugsize_unit_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('station', 'name'), name='unique_customer_name_per_station'),
        ),
    ]
