# Generated by Django 5.2 on 2026-03-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0039_add_offline_fields_to_customer'),
        ('wrsm_app', '0041_customer_unique_customer_name_per_station'),
    ]

    operations = [
    ]
