# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0042_merge_20260302_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_payments', to='wrsm_app.paymenttype'),
        ),
    ]



