# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0043_sales_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='amount_given',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount tendered (for Cash); used for change calculation', max_digits=12, null=True),
        ),
    ]



