# Generated by Django 5.2 on 2026-04-06 09:31

import django.db.models.deletion
from django.db import migrations, models


def backfill_initial_prices(apps, schema_editor):
    Product = apps.get_model('wrsm_app', 'Product')
    ProductPriceHistory = apps.get_model('wrsm_app', 'ProductPriceHistory')
    for p in Product.objects.exclude(unit_price__isnull=True).iterator():
        ProductPriceHistory.objects.create(
            product_id=p.pk,
            station_id=p.station_id,
            previous_price=None,
            new_price=p.unit_price,
            changed_by_id=getattr(p, 'created_by_id', None),
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wrsm_app', '0044_sales_amount_given'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_price_changes_recorded', to='wrsm_app.profile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history_entries', to='wrsm_app.product')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_price_history_entries', to='wrsm_app.station')),
            ],
            options={
                'verbose_name_plural': 'Product price history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.RunPython(backfill_initial_prices, noop_reverse),
    ]
